#
# Author Fanxu
# Email 746439274@qq.com
#
mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  command: sh -c 'mysqld'
  container_name: mysql
php:
  image: php:latest
  ports:
    - "9000:9000"
  command: sh -c 'php-fpm'
  container_name: php
  links:
    - mysql:mysql
nginx:
  image: nginx:latest
  ports:
    - "80:80"
  command: sh -c 'nginx -g "daemon off;"'
  volumes:
    - /var/www:/var/www
  container_name: nginx
  links:
    - php:php